-- MySQL Script generated by MySQL Workbench
-- Wed Jul 27 15:09:44 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `curp` VARCHAR(18) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `ap_paterno` VARCHAR(45) NOT NULL,
  `ap_materno` VARCHAR(45) NOT NULL,
  `edad` INT(3) NOT NULL,
  `g_etnico` TINYINT NOT NULL,
  `colonia` VARCHAR(100) NOT NULL,
  `calle` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(15) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `tel_cel` VARCHAR(20) NOT NULL,
  `tel_fijo` VARCHAR(20) NOT NULL,
  `grado` VARCHAR(3) NOT NULL,
  `promedio` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `curp_UNIQUE` (`curp` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`municipios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`municipios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `estados_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_municipios_estados1_idx` (`estados_id` ASC) VISIBLE,
  CONSTRAINT `fk_municipios_estados1`
    FOREIGN KEY (`estados_id`)
    REFERENCES `mydb`.`estados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`instituciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instituciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`instituciones` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`carreras` ;

CREATE TABLE IF NOT EXISTS `mydb`.`carreras` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `instituciones_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_carreras_instituciones_idx` (`instituciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_carreras_instituciones`
    FOREIGN KEY (`instituciones_id`)
    REFERENCES `mydb`.`instituciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carreras_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`carreras_has_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`carreras_has_users` (
  `carreras_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`carreras_id`, `users_id`),
  INDEX `fk_carreras_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_carreras_has_users_carreras1_idx` (`carreras_id` ASC) VISIBLE,
  CONSTRAINT `fk_carreras_has_users_carreras1`
    FOREIGN KEY (`carreras_id`)
    REFERENCES `mydb`.`carreras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carreras_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`municipios_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`municipios_has_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`municipios_has_users` (
  `municipios_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`municipios_id`, `users_id`),
  INDEX `fk_municipios_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_municipios_has_users_municipios1_idx` (`municipios_id` ASC) VISIBLE,
  CONSTRAINT `fk_municipios_has_users_municipios1`
    FOREIGN KEY (`municipios_id`)
    REFERENCES `mydb`.`municipios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_municipios_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudio_socioeconomico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`estudio_socioeconomico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`estudio_socioeconomico` (
  `id` INT NOT NULL,
  `campos` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users_has_estudio_socioeconomico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users_has_estudio_socioeconomico` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users_has_estudio_socioeconomico` (
  `users_id` INT NOT NULL,
  `estudio_socioeconomico_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `estudio_socioeconomico_id`),
  INDEX `fk_users_has_estudio_socioeconomico_estudio_socioeconomico1_idx` (`estudio_socioeconomico_id` ASC) VISIBLE,
  INDEX `fk_users_has_estudio_socioeconomico_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_estudio_socioeconomico_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_estudio_socioeconomico_estudio_socioeconomico1`
    FOREIGN KEY (`estudio_socioeconomico_id`)
    REFERENCES `mydb`.`estudio_socioeconomico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`convocatoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`convocatoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`convocatoria` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modalidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`modalidad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`modalidad` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `requisitos` LONGTEXT NOT NULL,
  `convocatoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modalidad_convocatoria1_idx` (`convocatoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_modalidad_convocatoria1`
    FOREIGN KEY (`convocatoria_id`)
    REFERENCES `mydb`.`convocatoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solicitudes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`solicitudes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`solicitudes` (
  `id` INT NOT NULL,
  `modalidad_id` INT NOT NULL,
  `estudio_socioeconomico_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_solicitudes_modalidad1_idx` (`modalidad_id` ASC) VISIBLE,
  INDEX `fk_solicitudes_estudio_socioeconomico1_idx` (`estudio_socioeconomico_id` ASC) VISIBLE,
  CONSTRAINT `fk_solicitudes_modalidad1`
    FOREIGN KEY (`modalidad_id`)
    REFERENCES `mydb`.`modalidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_estudio_socioeconomico1`
    FOREIGN KEY (`estudio_socioeconomico_id`)
    REFERENCES `mydb`.`estudio_socioeconomico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`configuracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`configuracion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`configuracion` (
  `id` INT NOT NULL,
  `logo` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
